"""Allow user_ai_model_id to be nullable

Revision ID: 79891d85cd73
Revises: 087353159fbe
Create Date: 2024-10-09 13:30:06.598868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79891d85cd73'
down_revision: Union[str, None] = '087353159fbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_transactions', 'user_ai_model_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_transactions', 'user_ai_model_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
