x-shared-parameters: &shared-parameters
  env_file:
    - ../../.env
  network_mode: "host"
  restart: always

x-db-dependency: &db-dependency
  depends_on:
    db:
      condition: service_started
    rabbitmq:
      condition: service_healthy

services:
  db:
    <<: *shared-parameters
    image: postgres:14-alpine
    container_name: debug_db
    volumes:
      - debug_psgsql_volume:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  pgadmin:
    <<: *shared-parameters
    image: dpage/pgadmin4:latest
    container_name: pgadmin    
    ports:
      - "8090:8090"
    restart: unless-stopped
    environment:
      - PGADMIN_LISTEN_PORT=8090
    volumes:
      - pgadmin_volume:/var/lib/pgadmin/
    depends_on:
      - db

  redis:
    <<: *shared-parameters
    image: redis:latest
    container_name: debug_redis
    command: >
      --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"

  rabbitmq:
    <<: *shared-parameters
    image: rabbitmq:3.13-management
    container_name: debug_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - debug_rabbitmq_volume:/var/lib/rabbitmq/:rw
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  celery:
    <<: [*shared-parameters, *db-dependency]
    build:
      context: ../../backend
      dockerfile: Dockerfile
    container_name: debug_celery
    command: ./src/conf/entrypoints/celery.sh

  celery-beat:
    <<: [*shared-parameters, *db-dependency]
    build:
      context: ../../backend
      dockerfile: Dockerfile
    container_name: debug_celery-beat
    command: ./src/conf/entrypoints/celery-beat.sh
    mem_limit: 1g
    cpus: "1.0"

  taskiq:
    <<: [*shared-parameters, *db-dependency]
    build:
      context: ../../backend
      dockerfile: Dockerfile
    container_name: debug_taskiq_worker
    command: ./src/conf/entrypoints/taskiq.sh

volumes:
  debug_psgsql_volume:
  pgadmin_volume:
  debug_rabbitmq_volume:
